try {
  ver
}
catch (e) {
  console.log(e);
}
finally {
  phantom.exit();
}
